### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by amber-h** [chiladieshack/chiladieshack.github.io#9]

**Comment by alison985** [comment]
How old do I have to be to participate in this event?

You must be at least 18 years of age by April 1, 2016.

**Comment by alison985** [comment]
What should I bring to the hackathon?
Your laptop and charger. Additionally, you should be ready to learn, contribute, and make a difference for a good cause!

**Comment by alison985** [comment]
What is a hackathon? 

A hackathon is a 24-36 hour programming event where people from various backgrounds come together, form teams, share ideas, and help each other build innovative projects. It is one of the best ways to meet new people, learn from mentors, and make cool stuff.

**Comment by alison985** [comment]
How are teams formed?
Teams will be formed in advance of the the hackathon by the group organizers based off of participants responses in their Eventbrite registration and the needs of the projects. Teams will be between 3 and 8 hackers, a coach, and an organizational liaison.

**Comment by alison985** [comment]
I'm a recruiter, can I attend your event?
If you would like to sponsor the Chi Ladies Hackathon, we welcome your sponsorship.

**Comment by amber-h** [comment]
When will I find out which team I am on? 

We will announce the teams on Friday during the Installfest, so make sure you are there to meet your team!

**Comment by CoralineAda** [comment]
Friday.

**Comment by amber-h** [comment]
Will food be provided? 

Yes. Dinner will be provided Friday as well as breakfast and lunch on Saturday thanks to our sponsors. We will make sure to accommodate any dietary restrictions as specified in your Eventbrite registration.
